### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by 499596986** [deepred5/vue-webpack-simple#1]
怎么我 下载下来。 然后  npm install ==>npm run  dev （提示 cross-env 不是内部或外部命令,）==>然后我 把（"cross-env NODE_ENV=development webpack-dev-server --open --hot",）中的  （cross-env NODE_ENV=development删掉,变成 webpack-dev-server --open --hot ）===》再次运行 还是报错

**Comment by deepred5** [comment]
@499596986 `npm install --save-dev cross-env`
